### ISSUE TITLE
Server shutdown - Airskif/Boat key use - [1.15.2 Forge]

### ISSUE THREAD

**Issue by Jergeric** [JSJBDEV/PlatosTransporters#12]
Aloha again, so there is no server message but the server still shuts down as soon as I click somewhere with the key from the seat (airplane). 

I tested a little bit more, cars work so far but airplanes don't do anything except turn with the player and boats are quite funny. 🙈😅

If you build a boat and sit down in the seat, the server crashes 🙈 have the crash report attached to it.

If you like, I can give you the address of our discord and our beta server to test it yourself.

If we can help you in any way, just let me know. 
We from the Magrathea Team, would like to use and support your mod. We all liked davincis-vessels and think your work for the community is great! 

Translated with www.DeepL.com/Translator (free version)

[crash-2020-08-16_07.37.05-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5080070/crash-2020-08-16_07.37.05-server.txt)

**Comment by JSJBDEV** [comment]
Looks like the error is in a different place but it's the same circumstance this time, will look into it

**Comment by iasoren** [comment]
I'm also experiencing the same crash. I'm using a forge server of 1.15.2 with the only other mod being WorldEdit. I've tried the most recent versions (1.2.1 and 1.2.2) for 1.15. I've also attached some crash logs. Let me know if there is anything I can do to help!

[crash-2020-08-16_09.05.34-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5080992/crash-2020-08-16_09.05.34-server.txt)
[crash-2020-08-16_09.07.21-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5080993/crash-2020-08-16_09.07.21-server.txt)
[crash-2020-08-16_09.08.21-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5080994/crash-2020-08-16_09.08.21-server.txt)
[crash-2020-08-16_09.11.23-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5080995/crash-2020-08-16_09.11.23-server.txt)
[crash-2020-08-16_09.12.23-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5080996/crash-2020-08-16_09.12.23-server.txt)

**Comment by JSJBDEV** [comment]
found the error, pushing update now

**Comment by JSJBDEV** [comment]
hey there, go check the new update 1.2.3 on CF that should fix this, reopen the issue if it persists!

**Comment by iasoren** [comment]
Alas that doesn't seem to have fixed it. Airships crash when trying to use them with the key in hand, and boats still crash when boarding.

[crash-2020-08-16_17.46.57-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5081650/crash-2020-08-16_17.46.57-server.txt)
[crash-2020-08-16_17.47.57-server.txt](https://github.com/JSJBDEV/PlatosTransporters/files/5081651/crash-2020-08-16_17.47.57-server.txt)

**Comment by JSJBDEV** [comment]
That error looks like it's in the same place so something has gone wrong somewhere xD I'll have a look at it again

**Comment by JSJBDEV** [comment]
found the actual error, for some reason forge has methods that only exist on client that just call methods that exist on both which is kinda strange

**Comment by lonelydriver51** [comment]
With the fabric version happening the same

**Comment by lonelydriver51** [comment]
1.16.1 version
